# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seel_res/GUI/E_MISCELLANEOUS/B/templates/remote.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(-1, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.channelLabel = QtWidgets.QLabel(self.frame_2)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout.addWidget(self.channelLabel, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.pubEdit = QtWidgets.QLineEdit(self.frame_2)
        self.pubEdit.setText("")
        self.pubEdit.setObjectName("pubEdit")
        self.gridLayout.addWidget(self.pubEdit, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.subEdit = QtWidgets.QLineEdit(self.frame_2)
        self.subEdit.setText("")
        self.subEdit.setObjectName("subEdit")
        self.gridLayout.addWidget(self.subEdit, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmdEdit = QtWidgets.QLineEdit(self.frame_4)
        self.cmdEdit.setObjectName("cmdEdit")
        self.gridLayout_3.addWidget(self.cmdEdit, 0, 0, 1, 1)
        self.sendID = QtWidgets.QLineEdit(self.frame_4)
        self.sendID.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sendID.setObjectName("sendID")
        self.gridLayout_3.addWidget(self.sendID, 0, 2, 1, 1)
        self.responseLabel = QtWidgets.QLabel(self.frame_4)
        self.responseLabel.setObjectName("responseLabel")
        self.gridLayout_3.addWidget(self.responseLabel, 1, 0, 1, 3)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        self.results = QtWidgets.QTextEdit(self.frame_3)
        self.results.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.results.setObjectName("results")
        self.gridLayout_2.addWidget(self.results, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setContentsMargins(-1, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.thingSpeakKey = QtWidgets.QLineEdit(self.frame_5)
        self.thingSpeakKey.setObjectName("thingSpeakKey")
        self.gridLayout_4.addWidget(self.thingSpeakKey, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.results_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.results_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.results_2.setObjectName("results_2")
        self.verticalLayout_4.addWidget(self.results_2)
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.thingSpeakInterval = QtWidgets.QSpinBox(self.frame_6)
        self.thingSpeakInterval.setMinimum(15)
        self.thingSpeakInterval.setMaximum(1000)
        self.thingSpeakInterval.setObjectName("thingSpeakInterval")
        self.gridLayout_5.addWidget(self.thingSpeakInterval, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.cmdEditThingSpeak = QtWidgets.QLineEdit(self.frame_6)
        self.cmdEditThingSpeak.setObjectName("cmdEditThingSpeak")
        self.gridLayout_5.addWidget(self.cmdEditThingSpeak, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox.toggled['bool'].connect(MainWindow.setListenState)
        self.pushButton_4.clicked.connect(MainWindow.resetKeys)
        self.pushButton_3.clicked.connect(MainWindow.execRemote)
        self.pushButton_6.clicked.connect(MainWindow.setThingSpeakCommand)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote access and publishing"))
        self.frame.setProperty("class", _translate("MainWindow", "PeripheralCollection"))
        self.frame_2.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.channelLabel.setText(_translate("MainWindow", "channel:"))
        self.checkBox.setText(_translate("MainWindow", "Listen to incoming messages"))
        self.pubEdit.setPlaceholderText(_translate("MainWindow", "publish key"))
        self.pushButton_4.setText(_translate("MainWindow", "Reset keys"))
        self.subEdit.setPlaceholderText(_translate("MainWindow", "subscriber key"))
        self.frame_3.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.frame_4.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.cmdEdit.setText(_translate("MainWindow", "get_version()"))
        self.sendID.setText(_translate("MainWindow", "0x02"))
        self.responseLabel.setText(_translate("MainWindow", "Response:"))
        self.pushButton_3.setText(_translate("MainWindow", "Execute on"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PubNub"))
        self.frame_5.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.thingSpeakKey.setToolTip(_translate("MainWindow", "Get a key from thingspeak.com by creating your own channel"))
        self.thingSpeakKey.setText(_translate("MainWindow", "H1OE0R294J0R6YQN"))
        self.thingSpeakKey.setPlaceholderText(_translate("MainWindow", "publish key"))
        self.label_2.setText(_translate("MainWindow", "ThingSpeak Key"))
        self.frame_6.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.thingSpeakInterval.setToolTip(_translate("MainWindow", "Set the interval for pushing data.\n"
"The rate limit for ThingSpeak.com is 15 seconds"))
        self.thingSpeakInterval.setSuffix(_translate("MainWindow", " Seconds"))
        self.pushButton_6.setText(_translate("MainWindow", "Set Command"))
        self.cmdEditThingSpeak.setText(_translate("MainWindow", "get_average_voltage(\'CH1\')"))
        self.cmdEditThingSpeak.setPlaceholderText(_translate("MainWindow", "Command to execute"))
        self.label.setText(_translate("MainWindow", "Update Interval"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ThingSpeak"))

